from __future__ import annotations

import io
import uuid
from datetime import date, datetime

from fastapi import APIRouter, Depends, File, UploadFile
from openpyxl import load_workbook
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user
from app.db.session import get_db
from app.models.clinic import Clinic
from app.models.implant import Implant
from app.models.patient import Patient
from app.models.user import User

router = APIRouter(tags=["implant-log-import"])

# Cell positions must match the template generated by PatientImplantLogForm.js
_PATIENT_FIELD_CELLS = {
    "name": "B3",
    "age": "B4",
    "gender": "B5",
    "phone": "B6",
    "email": "B7",
    "address": "B8",
    "medical_history": "B9",
    "clinic_name": "B10",
    "surgeon_name": "B11",
}
_IMPLANT_TABLE_START_ROW = 14
_IMPLANT_TABLE_ROWS = 12
_IMPLANT_COLUMNS = [
    "tooth_number", "implant_type", "brand", "diameter_mm", "length_mm",
    "insertion_torque", "connection_type", "surgical_approach", "arch",
    "jaw_region", "surgery_date", "cover_screw", "healing_abutment", "notes",
]


def _cell_value(ws, cell: str):
    v = ws[cell].value
    return v.strip() if isinstance(v, str) else v


def _parse_yes_no(v) -> bool:
    if isinstance(v, bool):
        return v
    if not v:
        return False
    return str(v).strip().lower() in ("yes", "y", "true", "1")


def _parse_date(v):
    if isinstance(v, datetime):
        return v.date()
    if isinstance(v, date):
        return v
    if isinstance(v, str) and v.strip():
        for fmt in ("%d-%m-%Y", "%Y-%m-%d", "%d/%m/%Y"):
            try:
                return datetime.strptime(v.strip(), fmt).date()
            except ValueError:
                continue
    return None


def _parse_float(v):
    if v in (None, ""):
        return None
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


async def _get_or_create_clinic_id(db: AsyncSession, org_id: uuid.UUID, name) -> str | None:
    if not name or not str(name).strip():
        return None
    name = str(name).strip()
    result = await db.execute(select(Clinic).where(Clinic.org_id == org_id, Clinic.name == name))
    clinic = result.scalar_one_or_none()
    if clinic:
        return str(clinic.id)
    clinic = Clinic(id=uuid.uuid4(), org_id=org_id, name=name)
    db.add(clinic)
    await db.flush()
    return str(clinic.id)


@router.post("/implant-log-import")
async def import_implant_log_files(
    files: list[UploadFile] = File(...),
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> dict:
    """
    Accepts one Excel file per patient (the template from PatientImplantLogForm.js).
    Each file creates one patient plus up to 12 implants from its log table.
    """
    results = []
    total_patients = 0
    total_implants = 0

    for upload in files:
        file_result = {
            "filename": upload.filename,
            "patient_name": None,
            "patient_id": None,
            "implants_created": 0,
            "errors": [],
        }
        try:
            content = await upload.read()
            wb = load_workbook(io.BytesIO(content), data_only=True)
            sheet_name = "Patient & Implant Log" if "Patient & Implant Log" in wb.sheetnames else wb.sheetnames[0]
            ws = wb[sheet_name]

            name = _cell_value(ws, _PATIENT_FIELD_CELLS["name"])
            if not name or not str(name).strip():
                file_result["errors"].append("Patient Name (cell B3) is empty — file skipped")
                results.append(file_result)
                continue
            name = str(name).strip()
            file_result["patient_name"] = name

            age_raw = _cell_value(ws, _PATIENT_FIELD_CELLS["age"])
            age = int(age_raw) if isinstance(age_raw, (int, float)) else None

            clinic_id = await _get_or_create_clinic_id(
                db, current_user.org_id, _cell_value(ws, _PATIENT_FIELD_CELLS["clinic_name"])
            )
            surgeon_name = _cell_value(ws, _PATIENT_FIELD_CELLS["surgeon_name"]) or None

            patient = Patient(
                id=uuid.uuid4(),
                org_id=current_user.org_id,
                doctor_id=current_user.id,
                name=name,
                age=age,
                gender=_cell_value(ws, _PATIENT_FIELD_CELLS["gender"]) or None,
                phone=_cell_value(ws, _PATIENT_FIELD_CELLS["phone"]) or None,
                email=_cell_value(ws, _PATIENT_FIELD_CELLS["email"]) or None,
                address=_cell_value(ws, _PATIENT_FIELD_CELLS["address"]) or None,
                medical_history=_cell_value(ws, _PATIENT_FIELD_CELLS["medical_history"]) or None,
            )
            db.add(patient)
            await db.flush()
            file_result["patient_id"] = str(patient.id)
            total_patients += 1

            for i in range(_IMPLANT_TABLE_ROWS):
                row_num = _IMPLANT_TABLE_START_ROW + i
                row_vals = {
                    col: ws.cell(row=row_num, column=idx + 1).value
                    for idx, col in enumerate(_IMPLANT_COLUMNS)
                }
                tooth = row_vals["tooth_number"]
                if tooth in (None, ""):
                    continue
                try:
                    implant = Implant(
                        id=uuid.uuid4(),
                        case_id=None,
                        patient_id=patient.id,
                        tooth_number=int(tooth),
                        implant_type=row_vals["implant_type"] or None,
                        brand=row_vals["brand"] or None,
                        diameter_mm=_parse_float(row_vals["diameter_mm"]),
                        length_mm=_parse_float(row_vals["length_mm"]),
                        insertion_torque=_parse_float(row_vals["insertion_torque"]),
                        connection_type=row_vals["connection_type"] or None,
                        surgical_approach=row_vals["surgical_approach"] or None,
                        arch=row_vals["arch"] or None,
                        jaw_region=row_vals["jaw_region"] or None,
                        surgery_date=_parse_date(row_vals["surgery_date"]),
                        cover_screw=_parse_yes_no(row_vals["cover_screw"]),
                        healing_abutment=_parse_yes_no(row_vals["healing_abutment"]),
                        clinical_notes=row_vals["notes"] or None,
                        clinic_id=clinic_id,
                        surgeon_name=surgeon_name,
                    )
                    db.add(implant)
                    file_result["implants_created"] += 1
                    total_implants += 1
                except (TypeError, ValueError) as exc:
                    file_result["errors"].append(f"Row {i + 1} (Tooth {tooth}): {exc}")

            await db.flush()
        except Exception as exc:
            file_result["errors"].append(f"Could not read file: {exc}")

        results.append(file_result)

    await db.commit()
    return {"results": results, "totals": {"patients": total_patients, "implants": total_implants}}
