"""add_fpd_indexes

Revision ID: 0be69855ee94
Revises: a62afaf594a4
Create Date: 2026-04-17 21:09:08.769988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be69855ee94'
down_revision: Union[str, Sequence[str], None] = 'a62afaf594a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_fpd_case_id', 'prosthetic_fpd', ['case_id'], unique=False)
    op.create_index('ix_fpd_patient_id', 'prosthetic_fpd', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fpd_patient_id', table_name='prosthetic_fpd')
    op.drop_index('ix_fpd_case_id', table_name='prosthetic_fpd')
    # ### end Alembic commands ###
