"""add_performance_indexes

Revision ID: 181597f90165
Revises: f4cdf580f0af
Create Date: 2026-04-17 20:58:36.278897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '181597f90165'
down_revision: Union[str, Sequence[str], None] = 'f4cdf580f0af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cases_doctor_id', 'cases', ['doctor_id'], unique=False)
    op.create_index('ix_cases_patient_id', 'cases', ['patient_id'], unique=False)
    op.create_index('ix_cases_status', 'cases', ['status'], unique=False)
    op.create_index('ix_clinics_org_id', 'clinics', ['org_id'], unique=False)
    op.create_index('ix_implants_case_id', 'implants', ['case_id'], unique=False)
    op.create_index('ix_implants_follow_up_date', 'implants', ['follow_up_date'], unique=False)
    op.create_index('ix_implants_patient_id', 'implants', ['patient_id'], unique=False)
    op.create_index('ix_patients_org_id', 'patients', ['org_id'], unique=False)
    op.create_index('ix_patients_org_id_deleted_at', 'patients', ['org_id', 'deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_patients_org_id_deleted_at', table_name='patients')
    op.drop_index('ix_patients_org_id', table_name='patients')
    op.drop_index('ix_implants_patient_id', table_name='implants')
    op.drop_index('ix_implants_follow_up_date', table_name='implants')
    op.drop_index('ix_implants_case_id', table_name='implants')
    op.drop_index('ix_clinics_org_id', table_name='clinics')
    op.drop_index('ix_cases_status', table_name='cases')
    op.drop_index('ix_cases_patient_id', table_name='cases')
    op.drop_index('ix_cases_doctor_id', table_name='cases')
    # ### end Alembic commands ###
