"""add_thumbnail_s3_key

Revision ID: a62afaf594a4
Revises: 181597f90165
Create Date: 2026-04-17 21:02:07.796428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a62afaf594a4'
down_revision: Union[str, Sequence[str], None] = '181597f90165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_images', sa.Column('thumbnail_s3_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_images', 'thumbnail_s3_key')
    # ### end Alembic commands ###
